copy_my_habr/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, shallow: true
  end

  resources :categories
  resources :tags

  get 'home' => 'posts#index'

   root 'welcome#index'

end

copy_my_habr/app/models/categories_post.rb
class CategoriesPost < ActiveRecord::Base
  belongs_to :category
  belongs_to :post

end

copy_my_habr/app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categories_posts
  has_many :posts, through: :categories_posts

  validates :name, presence: true, uniqueness: true

end

copy_my_habr/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :post_id, presence: true


  belongs_to :post
end

copy_my_habr/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :categories_posts
  has_many :categories, through: :categories_posts
  has_many :tags_posts
  has_many :tags, through: :tags_posts

  validates :title, presence: true
  validates :body, presence: true

def categories_titles
	categories.pluck(&;title).join(', ')
end	

end

copy_my_habr/app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  #validates :user_id, uniqueness: true
end

copy_my_habr/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tags_post
  has_many :posts, through: :tags_post
end

copy_my_habr/app/models/tags_post.rb
class TagsPost < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post

end

copy_my_habr/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
        redirect_to @category, notice: 'Category was successfully created.'
    else
        render :new
    end


  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end

  end


  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end





  private

  def category_params
    params.require(:category).permit(:name)
  end
end

copy_my_habr/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.post = @post

    if @comment.save
      redirect_to @post, notice: 'Комментарий успешно создан'
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
      redirect_to @comment.post, notice: 'Комментарий успешно удален'
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body, :post_id)
    end

end

copy_my_habr/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, category_ids: [])
    end
end

copy_my_habr/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
        redirect_to @tag, notice: 'Tag was successfully created.'
    else
        render :new
    end


  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update(tag_params)
      redirect_to @tag, notice: 'Tag was successfully updated.'
    else
      render :edit
    end

  end


  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path, notice: 'Tag was successfully destroyed.'
  end





  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

copy_my_habr/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

copy_my_habr/app/views/common/_errors.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(object.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

copy_my_habr/app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
    <%= render 'common/errors', object: @tag %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

copy_my_habr/app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

copy_my_habr/app/views/tags/index.html.erb
<h1>Тэги</h1>

<table class="table">
  <thead>
  <tr>
    <th>Тэг</th>

    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Новый тэг', new_tag_path %>

copy_my_habr/app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

copy_my_habr/app/views/tags/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>